from __future__ import annotations

import argparse
import bs4
import copy
import json
import logging
import os
import sys
import re
import glob
import typing
import collections

from packaging.version import Version

log = logging.getLogger(__name__)


def parse_arguments():
    command_parser = argparse.ArgumentParser(
        description="A professional tool to merge multiple pytest-html reports into a single one with consistent metadata.",  # noqa: E501
        epilog="Example: pgpro-pytest-html-merger -i ./reports -o summary.html --title 'Nightly Build'",  # noqa: E501
    )

    command_parser.add_argument(
        "--out",
        "-o",
        help="name of the output html report",
        action="store",
        dest="out",
        default="merged.html",
        type=str,
    )

    command_parser.add_argument(
        "--input-dir",
        "-i",
        help="directory containing html reports to merge (can be used multiple times)",  # noqa: E501
        action="append",
        dest="input_dirs",
        type=str,
    )

    command_parser.add_argument(
        "--title",
        "-t",
        help="title of the output html report",
        action="store",
        dest="title",
        type=str,
    )

    command_parser.add_argument(
        "--verbose",
        "-v",
        help="level of logging verbosity",
        default=3,
        action="count",
    )

    command_parser.add_argument(
        "html_files",
        help="html files generated by pytest-html",
        action="store",
        nargs="*",
        type=str,
    )

    # parse options
    options = command_parser.parse_args()

    return options


class ErrMsgGenerator:
    @staticmethod
    def gen_msg__env_prop_is_none(name: str):
        assert type(name) is str
        return "Env property [{}] is None.".format(
            name,
        )

    # --------------------------------------------------------------------
    @staticmethod
    def gen_msg__unsupported_env_prop_type(name: str, type_name: str):
        assert type(name) is str
        assert type(type_name) is str
        return "Unsupported env property [{}] type [{}].".format(
            name,
            type_name,
        )

    # --------------------------------------------------------------------
    @staticmethod
    def gen_msg__unknown_env_prop_type(name: str, type_name: str):
        assert type(name) is str
        assert type(type_name) is str
        return "Unknown env property [{}] type [{}].".format(
            name,
            type_name,
        )


class PytestReportEnvPropID:
    _part1: int
    _part2: typing.Optional[int]

    def __init__(self, part1: int, part2: typing.Optional[int]):
        assert type(part1) is int
        assert part2 is None or type(part2) is int
        self._part1 = part1
        self._part2 = part2
        return

    @property
    def part1(self) -> int:
        assert type(self._part1) is int
        return self._part1

    @property
    def part2(self) -> typing.Optional[int]:
        assert self._part2 is None or type(self._part2) is int
        return self._part2

    def __hash__(self) -> int:
        """
        Make the object hashable so it can be used as a dictionary key.
        We hash a tuple of its parts.
        """
        return hash((self._part1, self._part2))

    def __eq__(self, other: typing.Any) -> bool:
        """Check equality: both parts must match"""
        if not isinstance(other, PytestReportEnvPropID):
            return False
        return self.part1 == other.part1 and self.part2 == other.part2

    def __lt__(self, other: PytestReportEnvPropID) -> bool:
        """
        Comparison logic for sorting:
        1. Compare part1
        2. If part1 is equal, compare part2 (treating None as smaller
           than any int)
        """
        assert type(other) is PytestReportEnvPropID

        if self.part1 != other.part1:
            return self.part1 < other.part1

        # Handle None in part2 for sorting
        if self.part2 is None and other.part2 is not None:
            return True
        if self.part2 is not None and other.part2 is None:
            return False
        if self.part2 is None and other.part2 is None:
            return False

        assert type(self.part2) is int
        assert type(other.part2) is int

        return self.part2 < other.part2

    def __repr__(self) -> str:
        """Debug representation for our mega-project"""
        return "PytestReportEnvPropID(part1={}, part2={})".format(
            self.part1,
            self.part2,
        )


class PytestReportEnvProp:
    _name: str
    _id: PytestReportEnvPropID
    _value: typing.Any

    def __init__(
        self,
        name: str,
        id: PytestReportEnvPropID,
        value: typing.Any,
    ):
        assert type(name) is str
        assert type(id) is PytestReportEnvPropID
        assert value is not None
        assert __class__.helper__is_valid_value_type(
            value
        ), "name: {}, type: {}".format(name, type(value).__name__)
        self._name = name
        self._id = id
        self._value = value
        return

    @property
    def name(self) -> str:
        assert type(self._name) is str
        return self._name

    @property
    def id(self) -> PytestReportEnvPropID:
        assert type(self._id) is PytestReportEnvPropID
        return self._id

    @property
    def value(self) -> typing.Any:
        assert __class__.helper__is_valid_value_type(self._value)
        return self._value

    @staticmethod
    def helper__is_valid_value_type(value: typing.Any):
        if type(value) is str:
            return True
        if type(value) is PytestReportEnvPropList:
            return True
        return False


class PytestReportEnvPropList:
    m_items: typing.List[PytestReportEnvProp]

    def __init__(self):
        self.m_items = []
        return

    @staticmethod
    def create(
        report_id: int, env: typing.Dict[str, typing.Any]
    ) -> PytestReportEnvPropList:
        assert type(report_id) is int
        assert type(env) is dict
        propList = PytestReportEnvPropList()

        for n, v in env.items():
            assert type(n) is str

            if v is None:
                raise RuntimeError(
                    ErrMsgGenerator.gen_msg__env_prop_is_none(n),
                )

            if type(v) is str:
                v2 = v
            elif type(v) is dict:
                v2 = PytestReportEnvPropList.create(report_id, v)
            else:
                raise RuntimeError(
                    ErrMsgGenerator.gen_msg__unsupported_env_prop_type(
                        n,
                        type(v).__name__,
                    )
                )
            assert v2 is not None
            name, id_part2 = __class__.helper__parse_identity(n)

            propList.helper_add(
                name,
                PytestReportEnvPropID(report_id, id_part2),
                v2,
            )
            continue

        return propList

    def build_dict(self) -> typing.Dict[str, typing.Any]:
        ctx = __class__.tagBuildCtx()
        self.helper__build_ids(ctx)

        # --- Stable numbering logic ---
        # Sort all found IDs to ensure {1}, {2} etc. are always consistent
        sorted_ids = sorted(ctx.ids.keys())
        for i, ident in enumerate(sorted_ids, start=1):
            ctx.ids[ident] = i

        return self.helper__build_dict(ctx)

    class tagBuildCtx:
        ids: typing.Dict[PytestReportEnvPropID, int]

        def __init__(self):
            self.ids = {}
            return

    def helper__build_ids(self, ctx: tagBuildCtx) -> None:
        assert type(ctx) is __class__.tagBuildCtx
        for prop in self.m_items:
            # For stable numbering, we'll sort them in build_dict
            # before assigning numbers
            ctx.ids[prop.id] = 0
            if type(prop.value) is PytestReportEnvPropList:
                prop.value.helper__build_ids(ctx)
            continue
        return

    def helper__build_dict(
        self,
        ctx: tagBuildCtx,
    ) -> typing.Dict[str, typing.Any]:
        assert type(ctx) is __class__.tagBuildCtx

        names: typing.Dict[str, typing.Set[PytestReportEnvPropID]] = {}

        for prop in self.m_items:
            assert type(prop) is PytestReportEnvProp
            entries = names.get(prop.name, set())
            assert type(entries) is set
            entries.add(prop.id)
            names[prop.name] = entries
            continue

        result: typing.Dict[str, typing.Any] = {}

        for prop in self.m_items:
            assert type(prop) is PytestReportEnvProp

            if len(names[prop.name]) == 1:
                name = prop.name
            else:
                name = "{} {{{}}}".format(prop.name, ctx.ids[prop.id])

            if type(prop.value) is str:
                value = prop.value
            elif type(prop.value) is PytestReportEnvPropList:
                value = prop.value.helper__build_dict(ctx)
            else:
                raise RuntimeError(
                    ErrMsgGenerator.gen_msg__unknown_env_prop_type(
                        prop.name,
                        type(prop.value).__name__,
                    )
                )

            assert value is not None
            result[name] = value
            continue

        return result

    @staticmethod
    def helper__parse_identity(
        text: str,
    ) -> typing.Tuple[str, typing.Optional[int]]:
        """
        Parses a string in the format 'name {123}'.
        The id must be a numeric value.

        Compatible with Python 3.8+
        """
        # Regex breakdown:
        # ^(?P<name>.+?)  - Capture 'name' (non-greedy)
        # \s*             - Optional whitespace before the bracket
        # \{              - Open bracket
        # \s*(?P<id>\d+)\s* - Capture only digits and optional spaces inside {}
        # \}              - Close bracket
        # $               - End of string
        pattern = r"^(?P<name>.+?)\s*\{\s*(?P<id>\d+)\s*\}$"

        stripped_text = text.strip()
        match = re.match(pattern, stripped_text)

        if match:
            name = match.group("name").strip()
            # Convert to int since we guaranteed it's digits
            numeric_id = int(match.group("id"))
            return name, numeric_id

        # Fallback: whole string as name, ID as None
        return stripped_text, None

    def helper_add(
        self, name: str, id: PytestReportEnvPropID, value: typing.Any
    ) -> PytestReportEnvPropList:
        assert type(self.m_items) is list
        self.m_items.append(PytestReportEnvProp(name, id, value))
        return self


class PytestReportEnvAggregator:
    _result: PytestReportEnvPropList
    _index: typing.Dict[
        str,
        typing.List[typing.Tuple[int, PytestReportEnvProp]],
    ]

    # --------------------------------------------------------------------
    def __init__(self):
        self._result = PytestReportEnvPropList()
        self._index = {}
        return

    # --------------------------------------------------------------------
    @property
    def result(self) -> PytestReportEnvPropList:
        assert type(self._result) is PytestReportEnvPropList
        return self._result

    # --------------------------------------------------------------------
    def add(self, list: PytestReportEnvPropList) -> None:
        assert type(list) is PytestReportEnvPropList

        for prop in list.m_items:
            assert type(prop) is PytestReportEnvProp
            self.helper__add_prop(prop)
            continue
        return

    # --------------------------------------------------------------------
    def helper__add_prop(self, prop: PytestReportEnvProp) -> None:
        """
        Logic for merging properties:
        - If string values are identical: skip.
        - If both are lists: merge recursively and update existing.
        - If types are mixed or values differ: add as a new property.
        """
        assert type(prop) is PytestReportEnvProp
        entries = self._index.get(prop.name, [])

        for i_entry in range(len(entries)):
            entry = entries[i_entry]
            assert type(entry) is tuple
            assert len(entry) == 2
            assert type(entry[0]) is int
            assert type(entry[1]) is PytestReportEnvProp

            cp = entry[1]
            assert type(cp) is PytestReportEnvProp

            assert self._result.m_items[entry[0]] is cp

            # Case 1: Simple strings
            if type(prop.value) is str:
                if type(cp.value) is str:
                    if prop.value == cp.value:
                        return  # Already exists, skip
                continue

            # Case 2: Nested lists
            if type(prop.value) is PytestReportEnvPropList:
                if type(cp.value) is PytestReportEnvPropList:
                    # Recursive merge
                    sub_aggregator = PytestReportEnvAggregator()
                    sub_aggregator.add(cp.value)
                    sub_aggregator.add(prop.value)
                    new_p = PytestReportEnvProp(
                        cp.name,
                        cp.id,
                        sub_aggregator._result,
                    )
                    entries[i_entry] = (entry[0], new_p)
                    self._result.m_items[entry[0]] = new_p
                    return
                continue

            # Case 3: If we reach here with an unknown type, raise error
            # as requested in our mega-project style.
            raise RuntimeError(
                ErrMsgGenerator.gen_msg__unknown_env_prop_type(
                    prop.name, type(prop.value).__name__
                )
            )

        # If no match found, append as a new property
        entries.append((len(self._result.m_items), prop))
        self._index[prop.name] = entries
        self._result.m_items.append(prop)
        assert self._result.m_items[entries[-1][0]] is entries[-1][1]
        return


class PytestHTMLReportMerger:
    C_MININAL_PYTEST_HTML_VERSION = "4.0.2"

    _report_count: int
    _summary_count: int
    _summary_duration: float
    _summary_outcome: typing.Dict[str, int]
    _summary_tests: typing.Dict[str, typing.Any]
    _summary_envs: PytestReportEnvAggregator

    def __init__(self):
        self.base = None
        self._report_count = 0
        self._summary_count = 0
        self._summary_duration = 0.0
        self._summary_outcome = {}
        self._summary_tests = {}
        self._summary_envs = PytestReportEnvAggregator()
        return

    @staticmethod
    def _parse_frac(frac_str: str) -> float:
        assert type(frac_str) is str

        main_part = frac_str[:6]
        tail = frac_str[6:7]

        fraction_val = int(main_part) if main_part else 0
        power_of_10 = len(main_part)

        if tail and int(tail[0]) > 4:
            fraction_val += 1

        return fraction_val / (10**power_of_10)

    @staticmethod
    def _parse_duration_to_seconds(duration_val: typing.Any) -> float:
        if isinstance(duration_val, (int, float)):
            return float(duration_val)

        val_str = str(duration_val).strip()

        # 1. HH:MM:SS.mmmmmm (fractional is optional)
        hms_match = re.fullmatch(r"(\d+):(\d{2}):(\d{2})(?:\.(\d+))?", val_str)
        if hms_match:
            h, m, s, frac_str = hms_match.groups()

            total_seconds = int(h) * 3600 + int(m) * 60 + int(s)

            if frac_str is not None:
                total_seconds += __class__._parse_frac(frac_str)

            return float(total_seconds)

        # 2. Forma "number ms"
        ms_match = re.fullmatch(r"^(\d+(?:\.\d+)?)\s*ms$", val_str)
        if ms_match:
            return float(ms_match.group(1)) / 1000.0

        # 3. Clear seconds (with/without fraction)
        sec_match = re.fullmatch(r"^(\d+(?:\.\d+)?)$", val_str)
        if sec_match:
            return float(sec_match.group(1))

        raise ValueError(f"Invalid duration format: '{duration_val}'")

    @staticmethod
    def _format_time(duration):
        assert type(duration) is float
        assert duration >= 0

        if duration < 1:
            return "{} ms".format(int(duration * 1000))

        minutes, seconds = divmod(int(duration), 60)
        hours, minutes = divmod(minutes, 60)
        return "{:02d}:{:02d}:{:02d}".format(
            int(hours),
            int(minutes),
            int(seconds),
        )

    # --------------------------------------------------------------------
    @staticmethod
    def _extract_pytest_html_version(
        report_path,
        report_soup: bs4.BeautifulSoup,
    ) -> str:
        assert report_path is not None
        assert isinstance(report_soup, bs4.BeautifulSoup)

        """
        Robustly extract pytest-html version from the report footer/header.
        Example text: '... by pytest-html v4.0.2'
        """
        link = report_soup.find("a", href=re.compile(r"pytest-html"))
        if link is None:
            raise RuntimeError(
                "Report does not have section with pytest-html link.",
            )

        parent_text = link.parent.get_text()

        # Looking for pattern 'v' and digits (v4.0.2)
        match = re.search(r"v(\d+\.\d+\.\d+[\w\.]*)", parent_text)
        if not match:
            __class__._raise_err__cant_extract_report_version(
                report_path,
                parent_text,
            )

        return match.group(1)

    def _process_test(self, test: typing.Dict[str, typing.Any]) -> None:
        assert test is not None
        self._summary_duration += __class__._parse_duration_to_seconds(
            test.get("duration", 0.0)
        )
        test_outcome = test.get("result", "unknown").lower()
        self._summary_outcome[test_outcome] = (
            self._summary_outcome.get(test_outcome, 0) + 1
        )
        return

    def process_report(self, report_path):
        self._report_count += 1

        html_doc = ""
        with open(report_path, "r") as f:
            html_doc = f.read()
        soup = bs4.BeautifulSoup(html_doc, features="html.parser")

        html_version = __class__._extract_pytest_html_version(
            report_path,
            soup,
        )
        assert type(html_version) is str

        min_version = Version(__class__.C_MININAL_PYTEST_HTML_VERSION)
        if Version(html_version) < min_version:
            __class__._raise_err__unsupported_html_version(
                report_path,
                html_version,
            )

        # copy the base report
        if self.base is None:
            self.base = copy.copy(soup)

        # load json data from the current report
        report_data_container = soup.select("#data-container")[0]
        report_jsonblob = report_data_container.get("data-jsonblob")
        report_data = json.loads(report_jsonblob)

        # Calculate summary
        for _, test_data in report_data.get("tests", {}).items():
            if type(test_data) is list:
                # Reruns case ...
                assert len(test_data) > 0
                for test in test_data:
                    self._process_test(test)
            elif type(test_data) is dict:
                self._process_test(test_data)
            else:
                raise RuntimeError(
                    "Unexpected test_data type: {}.".format(
                        type(test_data).__name__,
                    ),
                )

            self._summary_count += 1
            new_test_key = str(self._summary_count)
            self._summary_tests[new_test_key] = copy.deepcopy(test_data)
            continue

        # Update envs
        prop_list = PytestReportEnvPropList.create(
            self._report_count,
            report_data.get("environment", {}),
        )
        self._summary_envs.add(prop_list)
        return

    def write_report(self, report_path, report_title):
        assert type(self.base) is not None
        if report_title is None:
            report_title = os.path.basename(report_path)

        # reset the title in the <head><title> element
        ele = self.base.select("#head-title")[0]
        ele.string = report_title

        # reset the title in the <body><h1> element
        ele = self.base.select("#title")[0]
        ele.string = report_title

        # save the updated total tests and total time.
        base_element = self.base.select(".run-count")[0]
        test_suffix = "test" if len(self._summary_tests) == 1 else "tests"
        base_element.string = "{} {} took {}.".format(
            len(self._summary_tests),
            test_suffix,
            __class__._format_time(self._summary_duration),
        )

        # update the filter counts
        for key in [
            "passed",
            "skipped",
            "failed",
            "error",
            "xfailed",
            "xpassed",
            "rerun",
            "retried",
        ]:
            value = self._summary_outcome.get(key, 0)

            # find the base's value for the key
            base_elements = self.base.select(f".filters .{key}")
            assert base_elements is not None

            if len(base_elements) == 0:
                # pytest-html 4.0.2 does not have "retried"
                log.debug(
                    f"Filter element for '{key}' not found in HTML template. Skipping UI update for this key."  # noqa: E501
                )
                continue

            assert len(base_elements) == 1, "key: {}, len: {}.".format(
                key, len(base_elements)
            )
            base_element0 = base_elements[0]
            assert base_element0.string is not None, "key: {}".format(key)
            matches = re.search(r"(\d+)", base_element0.string)
            base_value = int(matches.groups()[0])

            # save the updated count to the base
            base_element0.string = re.sub(
                r"\d+",
                str(value),
                base_element0.string,
            )

            # remove the base's disabled filter if the soup value was not zero
            if base_value == 0 and value > 0:
                ele = self.base.select(f"[data-test-result='{key}']")[0]
                del ele["disabled"]

        # load json data from the base report
        base_data_container = self.base.select("#data-container")[0]
        base_jsonblob = base_data_container.get("data-jsonblob")
        base_data = json.loads(base_jsonblob)

        # reset the title in the footer's data-jsonblob
        base_data["title"] = report_title

        base_data["tests"] = self._summary_tests
        base_data["environment"] = self._summary_envs.result.build_dict()

        # write the json data back to the html element's attribute
        base_data_container["data-jsonblob"] = json.dumps(base_data)

        # write to file
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(str(self.base.prettify(formatter="html5")))
        return

    @staticmethod
    def _raise_err__no_section_with_version(report_path) -> typing.NoReturn:
        err_msg = "Report [{}] does not have section with pytest-html link.".format(  # noqa: E501
            report_path
        )
        raise RuntimeError(err_msg)

    @staticmethod
    def _raise_err__cant_extract_report_version(
        report_path,
        text,
    ) -> typing.NoReturn:
        assert report_path is not None
        err_msg = "Cannot extract pytest-html version from {0!r}. Source file is [{1}]".format(  # noqa: E501
            text,
            report_path,
        )
        raise RuntimeError(err_msg)

    @staticmethod
    def _raise_err__unsupported_html_version(
        report_path, version: str
    ) -> typing.NoReturn:
        assert report_path is not None
        assert type(version) is str
        err_msg = "Source file [{}] has an unsupported version [{}]. The minimal supported version is [{}].".format(  # noqa: E501
            report_path,
            version,
            __class__.C_MININAL_PYTEST_HTML_VERSION,
        )
        raise RuntimeError(err_msg)


def main(arguments):
    raw_files = []
    has_errors = False

    # 1. Collect from directories
    if arguments.input_dirs:
        for directory in arguments.input_dirs:
            abs_dir = os.path.abspath(directory)
            if not os.path.isdir(abs_dir):
                log.error(f"Input directory does not exist: '{directory}'")
                has_errors = True
                continue

            pattern = os.path.join(abs_dir, "*.html")
            found = glob.glob(pattern)
            raw_files.extend(found)

    # 2. Collect from positional files
    if arguments.html_files:
        for f in arguments.html_files:
            abs_file = os.path.abspath(f)
            if not os.path.isfile(abs_file):
                log.error(
                    f"Invalid input: '{f}' is not a file or does not exist.",
                )
                has_errors = True
                continue
            raw_files.append(abs_file)

    # --- THE DEDUPLICATION CHECK ---
    counts = collections.Counter(raw_files)
    duplicates = [path for path, count in counts.items() if count > 1]

    if duplicates:
        for d in duplicates:
            log.error(f"Duplicate input file detected: '{d}'")
        has_errors = True

    # 3. Final check
    if has_errors:
        log.error(
            "Termination due to input errors (duplicates or missing files).",
        )
        sys.exit(1)

    if not raw_files:
        log.error("No HTML reports found to process.")
        return

    # 4. Sorting
    raw_files.sort()

    # Process each report file
    report_merger = PytestHTMLReportMerger()

    for infile in raw_files:
        log.info(f"Processing report: {infile}")
        report_merger.process_report(infile)

    # Finalize and write the aggregated report to disk
    report_merger.write_report(arguments.out, arguments.title)
    log.info(
        f"Successfully merged {len(raw_files)} reports into {arguments.out}",
    )
    return


def cli():
    arguments = parse_arguments()

    logging.basicConfig(level=int((6 - arguments.verbose) * 10))

    log.debug(f"opts = {arguments}")

    main(arguments)

    log.debug("exiting")
    return


if __name__ == "__main__":
    cli()
